<?php
/*
	define('db','mssql');
	define('host','208.118.63.9');
	define('port','');
	define('schema','DB_9D80D3_ControlSistema');
	define('user','DB_9D80D3_ControlSistema_admin');
	define('pass','fypass2580');
	define('driver','sqlsrv');
*/
	define('db','mysql');
	define('host','localhost');
	define('port','');
	define('schema','bd_controlsistema');
	define('user','root');
	define('pass','');
	define('driver','');
?>
